# Generated by Django 3.2.5 on 2021-07-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
