# Generated by Django 3.2.5 on 2021-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videos_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
