# Generated by Django 3.2.5 on 2021-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210705_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
