
BASE_PATH = 'video_app/base.html'
MODAL_PATH = 'video_app/modal/modal.html'
TITLE = 'title'
DESCRIPTION = 'description'
DATE = 'date'
PHOTO = 'photo'
VIDEOS = 'videos'
VIDEO_ID = 'video_id'
ID = 'id'
SNIPPET = 'snippet'
THUMBNAILS = 'thumbnails'
DEFAULT = 'default'
PUBLISHED_AT = 'publishedAt'
URL = 'url'
YOUTUBE_BASE_URL = 'https://www.youtube.com/watch?v='
YOUTUBE_BASE_API = "https://youtube.googleapis.com/youtube/v3/search?key="
API_KEY = 'api_key'
# 'AIzaSyBXXzS77zT4P-5U15_uhAD_9nT6vQCL8QM'
THRESHOLD_DATE = '2020-01-01T18:42:16Z'
ITEMS = 'items'
TYPE = 'type'
VIDEO = 'video'
QUERY = 'cricket'
PAGE_THRESHOLD  = '20'
PART_TYPE  = 'snippet'
PUBLISHED_AFTER = 'publishedAfter'
MAX_RESULTS  = 'maxResults'
PART  = 'part'
ORDER = 'order'
QU = 'q'
LAST_MODIFIED = ''
TIMESTAMP_FORMAT = '%Y-%m-%d %H:%M:%S'
ENTRIES= 'entries'
ICONTAINS = '__icontains'
IEXACT = '__iexact'
NAME = 'name'
POST = 'POST'
GET  = 'GET'
BLANK = ''
API_KEYS = 'api_keys'
FREQUENCY = 10

# MESSAGES
SUCCESS = 'Added Successfully'
BLANK_MESSAGE = 'Blank name or key'
DUPLICATE = 'Duplicate name or key'
FETCHED_RESULT = "Fetched Result !!"
LIMIT_EXHAUSTED = 'Exhausted Limit for api Key: '
LAST_MODIFIED_ON ='Last modified on :'

# VIEWS
DASHBOARD = 'video_app:dashboard'